version: '3.8'

services:
  api:
    container_name: 'todo_api'
    build: 
      context: .
      dockerfile: api.Dockerfile
    ports:
    - "8080:8080"
    depends_on:
      - db
    volumes:
    - .:/app/
  db:
    image: mysql:8.0
    container_name: todo_db
    platform: linux/amd64
    volumes:
      - my-data:/var/lib/mysql
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=golang_api
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - my-network

networks:
  my-network:
    name: my-network

volumes:
  my-data:
    name: my-data